# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{forest}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Makoto Inoue"]
  s.date = %q{2010-11-02}
  s.default_executable = %q{forest}
  s.description = %q{A simple collection class to aggregate tree objects.
    It takes [Adjacency List](http://sqlsummit.com/AdjacencyList.htm) as input, shows some stats and the top x biggest trees.}
  s.executables = ["forest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/forest",
     "examples/input.csv",
     "forest.gemspec",
     "lib/forest.rb",
     "test/test_forest.rb"
  ]
  s.homepage = %q{http://github.com/makoto/forest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple collection class to aggregate tree objects}
  s.test_files = [
    "test/test_forest.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubytree>, [">= 0"])
    else
      s.add_dependency(%q<rubytree>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubytree>, [">= 0"])
  end
end

